/**
 * 路由实例与静态路由配置
 * 静态路由包含 /login、/register、/401、/403、/404、/500
 */
import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'

export const staticRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: () => import('@/layouts/AdminLayout.vue'),
    redirect: '/dashboard/workspace',
    children: [
      // 分组父路径默认重定向 (避免敲到 /system 等出现空白)
      { path: 'dashboard', redirect: '/dashboard/workspace' },
      { path: 'system', redirect: '/system/user' },
      { path: 'content', redirect: '/content/article' },
      { path: 'components', redirect: '/components/editor' },
      { path: 'charts', redirect: '/charts/line' },
      { path: 'charts/g2', redirect: '/charts/g2-line' },
      { path: 'charts/g6', redirect: '/charts/g6-graph' },
      { path: 'hooks', redirect: '/hooks/use-loading' },
      { path: 'features', redirect: '/features/dayjs' },
      { path: 'ui', redirect: '/ui/button' },
      { path: 'permission', redirect: '/permission/demo' },
      { path: 'rules', redirect: '/rules/maze' },
      { path: 'ai', redirect: '/ai/chat' },
      { path: 'multi-level', redirect: '/multi-level/1-1' },
      { path: 'multi-level/1-2', redirect: '/multi-level/1-2-1' },
      { path: 'multi-level/1-3', redirect: '/multi-level/1-3-1' },
      { path: 'multi-level/1-3-2', redirect: '/multi-level/1-3-2-1' },
      { path: 'multi-level/1-4', redirect: '/multi-level/1-4-1' },
      { path: 'multi-level/1-4-2', redirect: '/multi-level/1-4-2-1' },
      { path: 'multi-level/1-5', redirect: '/multi-level/1-5-1-1' },
      { path: 'multi-level/1-5-1', redirect: '/multi-level/1-5-1-1' },
      { path: 'multi-level/1-5-2', redirect: '/multi-level/1-5-2-1' },
      // 业务示例分组重定向
      { path: 'multi-level/biz', redirect: '/multi-level/biz/chat/wechat' },
      { path: 'multi-level/biz/chat', redirect: '/multi-level/biz/chat/wechat' },
      { path: 'multi-level/biz/ecom', redirect: '/multi-level/biz/ecom/taobao' },
      { path: 'multi-level/biz/video', redirect: '/multi-level/biz/video/bilibili' },
      // Dashboard group
      {
        path: 'dashboard/workspace',
        name: 'Workspace',
        component: () => import('@/views/dashboard/WorkspacePage.vue'),
        meta: { title: '工作台' },
      },
      {
        path: 'dashboard/analytics',
        name: 'Analytics',
        component: () => import('@/views/dashboard/AnalyticsPage.vue'),
        meta: { title: '数据分析' },
      },
      // System group
      {
        path: 'system/user',
        name: 'UserManagement',
        component: () => import('@/views/system/UserManagement.vue'),
        meta: { title: '用户管理' },
      },
      {
        path: 'system/role',
        name: 'RoleManagement',
        component: () => import('@/views/system/RoleManagement.vue'),
        meta: { title: '角色管理' },
      },
      {
        path: 'system/menu',
        name: 'MenuManagement',
        component: () => import('@/views/system/MenuManagement.vue'),
        meta: { title: '菜单管理' },
      },
      {
        path: 'system/department',
        name: 'DepartmentManagement',
        component: () => import('@/views/system/DepartmentManagement.vue'),
        meta: { title: '部门管理' },
      },
      // Content group
      {
        path: 'content/article',
        name: 'ArticleManagement',
        component: () => import('@/views/content/ArticleManagement.vue'),
        meta: { title: '文章管理' },
      },
      {
        path: 'content/category',
        name: 'CategoryManagement',
        component: () => import('@/views/content/CategoryManagement.vue'),
        meta: { title: '分类管理' },
      },
      {
        path: 'content/tag',
        name: 'TagManagement',
        component: () => import('@/views/content/TagManagement.vue'),
        meta: { title: '标签管理' },
      },
      // Components group
      {
        path: 'components/editor',
        name: 'EditorDemo',
        component: () => import('@/views/components/EditorDemo.vue'),
        meta: { title: '富文本编辑器' },
      },
      {
        path: 'components/drag',
        name: 'DragDemo',
        component: () => import('@/views/components/DragDemo.vue'),
        meta: { title: '拖拽列表' },
      },
      {
        path: 'components/drag-kanban',
        name: 'DragKanbanDemo',
        component: () => import('@/views/components/DragKanbanDemo.vue'),
        meta: { title: '看板拖拽' },
      },
      {
        path: 'components/drag-tree',
        name: 'DragNestedTreeDemo',
        component: () => import('@/views/components/DragNestedTreeDemo.vue'),
        meta: { title: '嵌套树拖拽' },
      },
      {
        path: 'components/drag-grid',
        name: 'DragGridDemo',
        component: () => import('@/views/components/DragGridDemo.vue'),
        meta: { title: '拖拽排序网格' },
      },
      {
        path: 'components/drag-native',
        name: 'DragNativeDemo',
        component: () => import('@/views/components/DragNativeDemo.vue'),
        meta: { title: '原生 HTML5 拖放' },
      },
      {
        path: 'components/editor-markdown',
        name: 'EditorMarkdownDemo',
        component: () => import('@/views/components/EditorMarkdownDemo.vue'),
        meta: { title: 'Markdown 编辑器' },
      },
      {
        path: 'components/editor-code',
        name: 'EditorCodeDemo',
        component: () => import('@/views/components/EditorCodeDemo.vue'),
        meta: { title: '代码编辑器' },
      },
      {
        path: 'components/editor-light',
        name: 'EditorLightDemo',
        component: () => import('@/views/components/EditorLightDemo.vue'),
        meta: { title: '轻量富文本' },
      },
      {
        path: 'components/editor-reader',
        name: 'EditorReaderDemo',
        component: () => import('@/views/components/EditorReaderDemo.vue'),
        meta: { title: '文档阅读器' },
      },
      {
        path: 'components/icons',
        name: 'IconsDemo',
        component: () => import('@/views/components/IconsDemo.vue'),
        meta: { title: '图标展示' },
      },
      // Charts group - 25 chart types
      {
        path: 'charts/line',
        name: 'LineChart',
        component: () => import('@/views/charts/LineChart.vue'),
        meta: { title: '折线图' },
      },
      {
        path: 'charts/area',
        name: 'AreaChart',
        component: () => import('@/views/charts/AreaChart.vue'),
        meta: { title: '面积图' },
      },
      {
        path: 'charts/bar',
        name: 'BarChart',
        component: () => import('@/views/charts/BarChart.vue'),
        meta: { title: '柱状图' },
      },
      {
        path: 'charts/horizontal-bar',
        name: 'HorizontalBar',
        component: () => import('@/views/charts/HorizontalBar.vue'),
        meta: { title: '横向柱状图' },
      },
      {
        path: 'charts/pie',
        name: 'PieChart',
        component: () => import('@/views/charts/PieChart.vue'),
        meta: { title: '饼图' },
      },
      {
        path: 'charts/doughnut',
        name: 'DoughnutChart',
        component: () => import('@/views/charts/DoughnutChart.vue'),
        meta: { title: '环形图' },
      },
      {
        path: 'charts/scatter',
        name: 'ScatterChart',
        component: () => import('@/views/charts/ScatterChart.vue'),
        meta: { title: '散点图' },
      },
      {
        path: 'charts/radar',
        name: 'RadarChart',
        component: () => import('@/views/charts/RadarChart.vue'),
        meta: { title: '雷达图' },
      },
      {
        path: 'charts/funnel',
        name: 'FunnelChart',
        component: () => import('@/views/charts/FunnelChart.vue'),
        meta: { title: '漏斗图' },
      },
      {
        path: 'charts/gauge',
        name: 'GaugeChart',
        component: () => import('@/views/charts/GaugeChart.vue'),
        meta: { title: '仪表盘图' },
      },
      {
        path: 'charts/heatmap',
        name: 'HeatmapChart',
        component: () => import('@/views/charts/HeatmapChart.vue'),
        meta: { title: '热力图' },
      },
      {
        path: 'charts/treemap',
        name: 'TreemapChart',
        component: () => import('@/views/charts/TreemapChart.vue'),
        meta: { title: '矩形树图' },
      },
      {
        path: 'charts/sunburst',
        name: 'SunburstChart',
        component: () => import('@/views/charts/SunburstChart.vue'),
        meta: { title: '旭日图' },
      },
      {
        path: 'charts/sankey',
        name: 'SankeyChart',
        component: () => import('@/views/charts/SankeyChart.vue'),
        meta: { title: '桑基图' },
      },
      {
        path: 'charts/candlestick',
        name: 'CandlestickChart',
        component: () => import('@/views/charts/CandlestickChart.vue'),
        meta: { title: 'K线图' },
      },
      {
        path: 'charts/boxplot',
        name: 'BoxplotChart',
        component: () => import('@/views/charts/BoxplotChart.vue'),
        meta: { title: '箱线图' },
      },
      {
        path: 'charts/waterfall',
        name: 'WaterfallChart',
        component: () => import('@/views/charts/WaterfallChart.vue'),
        meta: { title: '瀑布图' },
      },
      {
        path: 'charts/mixed',
        name: 'MixedChart',
        component: () => import('@/views/charts/MixedChart.vue'),
        meta: { title: '混合图' },
      },
      {
        path: 'charts/stacked-bar',
        name: 'StackedBar',
        component: () => import('@/views/charts/StackedBar.vue'),
        meta: { title: '堆叠柱状图' },
      },
      {
        path: 'charts/stacked-area',
        name: 'StackedArea',
        component: () => import('@/views/charts/StackedArea.vue'),
        meta: { title: '堆叠面积图' },
      },
      {
        path: 'charts/polar',
        name: 'PolarChart',
        component: () => import('@/views/charts/PolarChart.vue'),
        meta: { title: '极坐标图' },
      },
      {
        path: 'charts/rose',
        name: 'RoseChart',
        component: () => import('@/views/charts/RoseChart.vue'),
        meta: { title: '南丁格尔玫瑰图' },
      },
      {
        path: 'charts/parallel',
        name: 'ParallelChart',
        component: () => import('@/views/charts/ParallelChart.vue'),
        meta: { title: '平行坐标图' },
      },
      {
        path: 'charts/theme-river',
        name: 'ThemeRiverChart',
        component: () => import('@/views/charts/ThemeRiverChart.vue'),
        meta: { title: '主题河流图' },
      },
      {
        path: 'charts/graph',
        name: 'GraphChart',
        component: () => import('@/views/charts/GraphChart.vue'),
        meta: { title: '关系图' },
      },
      // AntV G2 / G6 charts
      {
        path: 'charts/g2-line',
        name: 'G2LineChart',
        component: () => import('@/views/charts/g2/G2LineDemo.vue'),
        meta: { title: 'G2 折线图' },
      },
      {
        path: 'charts/g2-bar',
        name: 'G2BarChart',
        component: () => import('@/views/charts/g2/G2BarDemo.vue'),
        meta: { title: 'G2 柱状图' },
      },
      {
        path: 'charts/g2-scatter',
        name: 'G2ScatterChart',
        component: () => import('@/views/charts/g2/G2ScatterMatrixDemo.vue'),
        meta: { title: 'G2 高级散点图' },
      },
      {
        path: 'charts/g6-graph',
        name: 'G6GraphChart',
        component: () => import('@/views/charts/g6/G6GraphDemo.vue'),
        meta: { title: 'G6 关系图' },
      },
      {
        path: 'charts/g6-org',
        name: 'G6OrgTreeChart',
        component: () => import('@/views/charts/g6/G6OrgTreeDemo.vue'),
        meta: { title: 'G6 组织树' },
      },
      {
        path: 'charts/g6-bracket',
        name: 'G6BracketChart',
        component: () => import('@/views/charts/g6/G6BracketDemo.vue'),
        meta: { title: 'G6 赛事对阵图' },
      },
      // Hooks group
      { path: 'hooks/use-loading', name: 'UseLoadingDemo', component: () => import('@/views/hooks/UseLoadingDemo.vue'), meta: { title: 'useLoading' } },
      { path: 'hooks/use-pagination', name: 'UsePaginationDemo', component: () => import('@/views/hooks/UsePaginationDemo.vue'), meta: { title: 'usePagination' } },
      { path: 'hooks/use-permission', name: 'UsePermissionDemo', component: () => import('@/views/hooks/UsePermissionDemo.vue'), meta: { title: 'usePermission' } },
      { path: 'hooks/use-sms-countdown', name: 'UseSmsCountdownDemo', component: () => import('@/views/hooks/UseSmsCountdownDemo.vue'), meta: { title: 'useSmsCountdown' } },
      { path: 'hooks/use-local-storage', name: 'UseLocalStorageDemo', component: () => import('@/views/hooks/UseLocalStorageDemo.vue'), meta: { title: 'useLocalStorage' } },
      { path: 'hooks/use-clipboard', name: 'UseClipboardDemo', component: () => import('@/views/hooks/UseClipboardDemo.vue'), meta: { title: 'useClipboard' } },
      { path: 'hooks/use-debounce-fn', name: 'UseDebounceFnDemo', component: () => import('@/views/hooks/UseDebounceFnDemo.vue'), meta: { title: 'useDebounceFn' } },
      { path: 'hooks/use-throttle-fn', name: 'UseThrottleFnDemo', component: () => import('@/views/hooks/UseThrottleFnDemo.vue'), meta: { title: 'useThrottleFn' } },
      { path: 'hooks/use-window-size', name: 'UseWindowSizeDemo', component: () => import('@/views/hooks/UseWindowSizeDemo.vue'), meta: { title: 'useWindowSize' } },
      { path: 'hooks/use-event-listener', name: 'UseEventListenerDemo', component: () => import('@/views/hooks/UseEventListenerDemo.vue'), meta: { title: 'useEventListener' } },
      // Features group
      {
        path: 'features/i18n',
        name: 'I18nDemo',
        component: () => import('@/views/features/I18nDemo.vue'),
        meta: { title: '国际化' },
      },
      {
        path: 'features/clipboard',
        name: 'ClipboardDemo',
        component: () => import('@/views/features/ClipboardDemo.vue'),
        meta: { title: '剪贴板' },
      },
      {
        path: 'features/print',
        name: 'PrintDemo',
        component: () => import('@/views/features/PrintDemo.vue'),
        meta: { title: '打印' },
      },
      {
        path: 'features/qrcode',
        name: 'QrcodeDemo',
        component: () => import('@/views/features/QrcodeDemo.vue'),
        meta: { title: 'QRCode 二维码' },
      },
      {
        path: 'features/crypto',
        name: 'CryptoDemo',
        component: () => import('@/views/features/CryptoDemo.vue'),
        meta: { title: 'CryptoJS 加解密' },
      },
      {
        path: 'features/jszip',
        name: 'JszipDemo',
        component: () => import('@/views/features/JszipDemo.vue'),
        meta: { title: 'JSZip 打包下载' },
      },
      {
        path: 'features/xlsx',
        name: 'XlsxDemo',
        component: () => import('@/views/features/XlsxDemo.vue'),
        meta: { title: 'SheetJS Excel' },
      },
      {
        path: 'features/papaparse',
        name: 'PapaparseDemo',
        component: () => import('@/views/features/PapaparseDemo.vue'),
        meta: { title: 'PapaParse CSV' },
      },
      {
        path: 'features/mock',
        name: 'MockDemo',
        component: () => import('@/views/features/MockDemo.vue'),
        meta: { title: 'MockJS 模拟数据' },
      },
      {
        path: 'features/nprogress',
        name: 'NprogressDemo',
        component: () => import('@/views/features/NprogressDemo.vue'),
        meta: { title: 'NProgress 进度条' },
      },
      {
        path: 'features/dayjs',
        name: 'DayjsDemo',
        component: () => import('@/views/features/DayjsDemo.vue'),
        meta: { title: 'dayjs 日期处理' },
      },
      {
        path: 'features/lodash',
        name: 'LodashDemo',
        component: () => import('@/views/features/LodashDemo.vue'),
        meta: { title: 'lodash 工具函数' },
      },
      // Components - Charts overview
      {
        path: 'components/charts',
        name: 'ChartsDemo',
        component: () => import('@/views/components/ChartsDemo.vue'),
        meta: { title: '图表概览' },
      },
      // UI Components
      { path: 'ui/button', name: 'ButtonDemo', component: () => import('@/views/ui/ButtonDemo.vue'), meta: { title: 'Button 按钮' } },
      { path: 'ui/input', name: 'InputDemo', component: () => import('@/views/ui/InputDemo.vue'), meta: { title: 'Input 输入框' } },
      { path: 'ui/form', name: 'FormDemo', component: () => import('@/views/ui/FormDemo.vue'), meta: { title: 'Form 表单' } },
      { path: 'ui/table', name: 'TableDemo', component: () => import('@/views/ui/TableDemo.vue'), meta: { title: 'Table 表格' } },
      { path: 'ui/modal', name: 'ModalDemo', component: () => import('@/views/ui/ModalDemo.vue'), meta: { title: 'Modal 模态框' } },
      { path: 'ui/drawer', name: 'DrawerDemo', component: () => import('@/views/ui/DrawerDemo.vue'), meta: { title: 'Drawer 抽屉' } },
      { path: 'ui/message', name: 'MessageDemo', component: () => import('@/views/ui/MessageDemo.vue'), meta: { title: 'Message 消息' } },
      { path: 'ui/notification', name: 'NotificationDemo', component: () => import('@/views/ui/NotificationDemo.vue'), meta: { title: 'Notification 通知' } },
      { path: 'ui/dialog', name: 'DialogDemo', component: () => import('@/views/ui/DialogDemo.vue'), meta: { title: 'Dialog 对话框' } },
      { path: 'ui/tabs', name: 'TabsDemo', component: () => import('@/views/ui/TabsDemo.vue'), meta: { title: 'Tabs 标签页' } },
      { path: 'ui/tag', name: 'TagDemo', component: () => import('@/views/ui/TagDemo.vue'), meta: { title: 'Tag 标签' } },
      { path: 'ui/select', name: 'SelectDemo', component: () => import('@/views/ui/SelectDemo.vue'), meta: { title: 'Select 选择器' } },
      { path: 'ui/date-picker', name: 'DatePickerDemo', component: () => import('@/views/ui/DatePickerDemo.vue'), meta: { title: 'DatePicker 日期选择' } },
      { path: 'ui/upload', name: 'UploadDemo', component: () => import('@/views/ui/UploadDemo.vue'), meta: { title: 'Upload 上传' } },
      { path: 'ui/tree', name: 'TreeDemo', component: () => import('@/views/ui/TreeDemo.vue'), meta: { title: 'Tree 树形控件' } },
      { path: 'ui/card', name: 'CardDemo', component: () => import('@/views/ui/CardDemo.vue'), meta: { title: 'Card 卡片' } },
      { path: 'ui/avatar', name: 'AvatarDemo', component: () => import('@/views/ui/AvatarDemo.vue'), meta: { title: 'Avatar 头像' } },
      { path: 'ui/badge', name: 'BadgeDemo', component: () => import('@/views/ui/BadgeDemo.vue'), meta: { title: 'Badge 徽标' } },
      { path: 'ui/progress', name: 'ProgressDemo', component: () => import('@/views/ui/ProgressDemo.vue'), meta: { title: 'Progress 进度条' } },
      { path: 'ui/timeline', name: 'TimelineDemo', component: () => import('@/views/ui/TimelineDemo.vue'), meta: { title: 'Timeline 时间线' } },
      { path: 'ui/alert', name: 'AlertDemo', component: () => import('@/views/ui/AlertDemo.vue'), meta: { title: 'Alert 警告' } },
      { path: 'ui/popover', name: 'PopoverDemo', component: () => import('@/views/ui/PopoverDemo.vue'), meta: { title: 'Popover 弹出框' } },
      { path: 'ui/tooltip', name: 'TooltipDemo', component: () => import('@/views/ui/TooltipDemo.vue'), meta: { title: 'Tooltip 文字提示' } },
      { path: 'ui/switch', name: 'SwitchDemo', component: () => import('@/views/ui/SwitchDemo.vue'), meta: { title: 'Switch 开关' } },
      { path: 'ui/slider', name: 'SliderDemo', component: () => import('@/views/ui/SliderDemo.vue'), meta: { title: 'Slider 滑块' } },
      { path: 'ui/transfer', name: 'TransferDemo', component: () => import('@/views/ui/TransferDemo.vue'), meta: { title: 'Transfer 穿梭框' } },
      { path: 'ui/collapse', name: 'CollapseDemo', component: () => import('@/views/ui/CollapseDemo.vue'), meta: { title: 'Collapse 折叠面板' } },
      { path: 'ui/dropdown', name: 'DropdownDemo', component: () => import('@/views/ui/DropdownDemo.vue'), meta: { title: 'Dropdown 下拉菜单' } },
      { path: 'ui/pagination', name: 'PaginationDemo', component: () => import('@/views/ui/PaginationDemo.vue'), meta: { title: 'Pagination 分页' } },
      { path: 'ui/steps', name: 'StepsDemo', component: () => import('@/views/ui/StepsDemo.vue'), meta: { title: 'Steps 步骤条' } },
      { path: 'ui/carousel', name: 'CarouselDemo', component: () => import('@/views/ui/CarouselDemo.vue'), meta: { title: 'Carousel 走马灯' } },
      { path: 'ui/descriptions', name: 'DescriptionsDemo', component: () => import('@/views/ui/DescriptionsDemo.vue'), meta: { title: 'Descriptions 描述列表' } },
      { path: 'ui/result', name: 'ResultDemo', component: () => import('@/views/ui/ResultDemo.vue'), meta: { title: 'Result 结果' } },
      { path: 'ui/skeleton', name: 'SkeletonDemo', component: () => import('@/views/ui/SkeletonDemo.vue'), meta: { title: 'Skeleton 骨架屏' } },
      { path: 'ui/spin', name: 'SpinDemo', component: () => import('@/views/ui/SpinDemo.vue'), meta: { title: 'Spin 加载' } },
      { path: 'ui/empty', name: 'EmptyDemo', component: () => import('@/views/ui/EmptyDemo.vue'), meta: { title: 'Empty 空状态' } },
      { path: 'ui/divider', name: 'DividerDemo', component: () => import('@/views/ui/DividerDemo.vue'), meta: { title: 'Divider 分割线' } },
      { path: 'ui/breadcrumb', name: 'BreadcrumbDemo', component: () => import('@/views/ui/BreadcrumbDemo.vue'), meta: { title: 'Breadcrumb 面包屑' } },
      { path: 'ui/menu', name: 'MenuDemo', component: () => import('@/views/ui/MenuDemo.vue'), meta: { title: 'Menu 菜单' } },
      { path: 'ui/color-picker', name: 'ColorPickerDemo', component: () => import('@/views/ui/ColorPickerDemo.vue'), meta: { title: 'ColorPicker 颜色选择' } },
      // Permission
      {
        path: 'permission-management',
        name: 'PermissionManagement',
        component: () => import('@/views/permission/PermissionManagement.vue'),
        meta: { title: '权限管理' },
      },
      {
        path: 'permission/demo',
        name: 'PermissionDemo',
        component: () => import('@/views/permission/PermissionDemo.vue'),
        meta: { title: '权限演示' },
      },
      // HTTP Status Code Pages
      { path: 'permission/http-200', name: 'Http200', component: () => import('@/views/error/Error200.vue'), meta: { title: '200 OK' } },
      { path: 'permission/http-202', name: 'Http202', component: () => import('@/views/error/Error202.vue'), meta: { title: '202 Accepted' } },
      { path: 'permission/http-204', name: 'Http204', component: () => import('@/views/error/Error204.vue'), meta: { title: '204 No Content' } },
      { path: 'permission/http-300', name: 'Http300', component: () => import('@/views/error/Error300.vue'), meta: { title: '300 Multiple Choices' } },
      { path: 'permission/http-302', name: 'Http302', component: () => import('@/views/error/Error302.vue'), meta: { title: '302 Found' } },
      { path: 'permission/http-400', name: 'Http400', component: () => import('@/views/error/Error400.vue'), meta: { title: '400 Bad Request' } },
      { path: 'permission/http-401', name: 'Http401', component: () => import('@/views/error/Error401.vue'), meta: { title: '401 Unauthorized' } },
      { path: 'permission/http-402', name: 'Http402', component: () => import('@/views/error/Error402.vue'), meta: { title: '402 Payment Required' } },
      { path: 'permission/http-403', name: 'Http403', component: () => import('@/views/error/Error403.vue'), meta: { title: '403 Forbidden' } },
      { path: 'permission/http-404', name: 'Http404', component: () => import('@/views/error/Error404.vue'), meta: { title: '404 Not Found' } },
      { path: 'permission/http-500', name: 'Http500', component: () => import('@/views/error/Error500.vue'), meta: { title: '500 Server Error' } },
      { path: 'permission/http-501', name: 'Http501', component: () => import('@/views/error/Error501.vue'), meta: { title: '501 Not Implemented' } },
      { path: 'permission/http-502', name: 'Http502', component: () => import('@/views/error/Error502.vue'), meta: { title: '502 Bad Gateway' } },
      { path: 'permission/http-503', name: 'Http503', component: () => import('@/views/error/Error503.vue'), meta: { title: '503 Unavailable' } },
      { path: 'permission/http-504', name: 'Http504', component: () => import('@/views/error/Error504.vue'), meta: { title: '504 Timeout' } },
      // Multi-level / 多级路由示例
      {
        path: 'multi-level/1-1',
        name: 'MultiLevel-1-1',
        component: () => import('@/views/multi-level/Level1-1.vue'),
        meta: { title: '1-1 Button 基础' },
      },
      {
        path: 'multi-level/1-2-1',
        name: 'MultiLevel-1-2-1',
        component: () => import('@/views/multi-level/Level1-2-1.vue'),
        meta: { title: '1-2-1 Tag 标签' },
      },
      {
        path: 'multi-level/1-3-1',
        name: 'MultiLevel-1-3-1',
        component: () => import('@/views/multi-level/Level1-3-1.vue'),
        meta: { title: '1-3-1 Card 卡片' },
      },
      {
        path: 'multi-level/1-3-2-1',
        name: 'MultiLevel-1-3-2-1',
        component: () => import('@/views/multi-level/Level1-3-2-1.vue'),
        meta: { title: '1-3-2-1 Modal + Drawer' },
      },
      {
        path: 'multi-level/1-4-1',
        name: 'MultiLevel-1-4-1',
        component: () => import('@/views/multi-level/Level1-4-1.vue'),
        meta: { title: '1-4-1 Form 基础' },
      },
      {
        path: 'multi-level/1-4-2-1',
        name: 'MultiLevel-1-4-2-1',
        component: () => import('@/views/multi-level/Level1-4-2-1.vue'),
        meta: { title: '1-4-2-1 DataTable 列表' },
      },
      {
        path: 'multi-level/1-4-2-2',
        name: 'MultiLevel-1-4-2-2',
        component: () => import('@/views/multi-level/Level1-4-2-2.vue'),
        meta: { title: '1-4-2-2 Tree + Transfer' },
      },
      {
        path: 'multi-level/1-5-1-1',
        name: 'MultiLevel-1-5-1-1',
        component: () => import('@/views/multi-level/Level1-5-1-1.vue'),
        meta: { title: '1-5-1-1 DataTable 自定义渲染' },
      },
      {
        path: 'multi-level/1-5-2-1',
        name: 'MultiLevel-1-5-2-1',
        component: () => import('@/views/multi-level/Level1-5-2-1.vue'),
        meta: { title: '1-5-2-1 综合表单' },
      },
      {
        path: 'multi-level/1-5-2-2',
        name: 'MultiLevel-1-5-2-2',
        component: () => import('@/views/multi-level/Level1-5-2-2.vue'),
        meta: { title: '1-5-2-2 综合 Dashboard' },
      },
      // 多级路由 - 业务示例
      { path: 'multi-level/biz/chat/wechat', name: 'BizChatWechat', component: () => import('@/views/multi-level/biz/ChatWechat.vue'), meta: { title: '聊天 · 微信风格' } },
      { path: 'multi-level/biz/chat/qq', name: 'BizChatQq', component: () => import('@/views/multi-level/biz/ChatQq.vue'), meta: { title: '聊天 · QQ 风格' } },
      { path: 'multi-level/biz/ecom/taobao', name: 'BizEcomTaobao', component: () => import('@/views/multi-level/biz/EcomTaobao.vue'), meta: { title: '电商 · 淘宝商品流' } },
      { path: 'multi-level/biz/ecom/pdd', name: 'BizEcomPdd', component: () => import('@/views/multi-level/biz/EcomPdd.vue'), meta: { title: '电商 · 拼多多拼团' } },
      { path: 'multi-level/biz/video/bilibili', name: 'BizVideoBilibili', component: () => import('@/views/multi-level/biz/VideoBilibili.vue'), meta: { title: '视频 · B 站弹幕' } },
      // Rules / 规则示例
      {
        path: 'rules/maze',
        name: 'MazeGenerator',
        component: () => import('@/views/rules/MazeGenerator.vue'),
        meta: { title: '迷宫生成与求解' },
      },
      {
        path: 'rules/sorting',
        name: 'SortingVisualizer',
        component: () => import('@/views/rules/SortingVisualizer.vue'),
        meta: { title: '排序可视化' },
      },
      // AI Components group
      { path: 'ai/playground', name: 'AiPlaygroundDemo', component: () => import('@/views/ai/PlaygroundDemo.vue'), meta: { title: 'Playground 综合对话' } },
      { path: 'ai/chat', name: 'AiChatDemo', component: () => import('@/views/ai/ChatDemo.vue'), meta: { title: 'Chat 聊天对话' } },
      { path: 'ai/streaming', name: 'AiStreamingDemo', component: () => import('@/views/ai/StreamingDemo.vue'), meta: { title: 'Streaming 流式输出' } },
      { path: 'ai/bubble', name: 'AiBubbleDemo', component: () => import('@/views/ai/BubbleDemo.vue'), meta: { title: 'Bubble 消息气泡' } },
      { path: 'ai/prompts', name: 'AiPromptsDemo', component: () => import('@/views/ai/PromptsDemo.vue'), meta: { title: 'Prompts 提示词' } },
      { path: 'ai/thinking', name: 'AiThinkingDemo', component: () => import('@/views/ai/ThinkingDemo.vue'), meta: { title: 'Thinking 思维链' } },
      { path: 'ai/suggestion', name: 'AiSuggestionDemo', component: () => import('@/views/ai/SuggestionDemo.vue'), meta: { title: 'Suggestion 指令建议' } },
      { path: 'ai/sender', name: 'AiSenderDemo', component: () => import('@/views/ai/SenderDemo.vue'), meta: { title: 'Sender 输入框' } },
      { path: 'ai/attachments', name: 'AiAttachmentsDemo', component: () => import('@/views/ai/AttachmentsDemo.vue'), meta: { title: 'Attachments 附件上传' } },
      { path: 'ai/welcome', name: 'AiWelcomeDemo', component: () => import('@/views/ai/WelcomeDemo.vue'), meta: { title: 'Welcome 欢迎页' } },
      { path: 'ai/conversations', name: 'AiConversationsDemo', component: () => import('@/views/ai/ConversationsDemo.vue'), meta: { title: 'Conversations 会话列表' } },
      { path: 'ai/bubble-list', name: 'AiBubbleListDemo', component: () => import('@/views/ai/BubbleListDemo.vue'), meta: { title: 'BubbleList 消息列表' } },
      { path: 'ai/file-card', name: 'AiFileCardDemo', component: () => import('@/views/ai/FileCardDemo.vue'), meta: { title: 'FileCard 文件卡片' } },
      { path: 'ai/typewriter', name: 'AiTypewriterDemo', component: () => import('@/views/ai/TypewriterDemo.vue'), meta: { title: 'Typewriter 打字机' } },
      { path: 'ai/reasoning-tree', name: 'AiReasoningTreeDemo', component: () => import('@/views/ai/ReasoningTreeDemo.vue'), meta: { title: 'ReasoningTree 推理树' } },
      { path: 'ai/mention-input', name: 'AiMentionInputDemo', component: () => import('@/views/ai/MentionInputDemo.vue'), meta: { title: 'MentionInput @提及输入' } },
      { path: 'ai/use-typing-stream', name: 'AiUseTypingStreamDemo', component: () => import('@/views/ai/UseTypingStreamDemo.vue'), meta: { title: 'useTypingStream' } },
      { path: 'ai/use-voice-record', name: 'AiUseVoiceRecordDemo', component: () => import('@/views/ai/UseVoiceRecordDemo.vue'), meta: { title: 'useVoiceRecord' } },
      { path: 'ai/use-chat-request', name: 'AiUseChatRequestDemo', component: () => import('@/views/ai/UseChatRequestDemo.vue'), meta: { title: 'useChatRequest' } },
      // About
      {
        path: 'about',
        name: 'About',
        component: () => import('@/views/about/AboutPage.vue'),
        meta: { title: '关于' },
      },
    ],
  },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/LoginPage.vue'),
    meta: { title: '登录' },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/register/RegisterPage.vue'),
    meta: { title: '注册' },
  },
  {
    path: '/401',
    name: 'Error401',
    component: () => import('@/views/error/Error401.vue'),
    meta: { title: '401' },
  },
  {
    path: '/403',
    name: 'Error403',
    component: () => import('@/views/error/Error403.vue'),
    meta: { title: '403' },
  },
  {
    path: '/404',
    name: 'Error404',
    component: () => import('@/views/error/Error404.vue'),
    meta: { title: '404' },
  },
  {
    path: '/500',
    name: 'Error500',
    component: () => import('@/views/error/Error500.vue'),
    meta: { title: '500' },
  },
  // catch-all 兜底：任何未声明的路径统一跳 404
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFoundCatchAll',
    redirect: '/404',
  },
]

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: staticRoutes,
})

export default router
