/**
 * 路由实例与静态路由配置
 * 静态路由包含 /login、/register、/401、/403、/404、/500
 */
import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'

export const staticRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    component: () => import('@/layouts/AdminLayout.vue'),
    redirect: '/dashboard/workspace',
    children: [
      // Dashboard group
      {
        path: 'dashboard/workspace',
        name: 'Workspace',
        component: () => import('@/views/dashboard/WorkspacePage.vue'),
        meta: { title: '工作台' },
      },
      {
        path: 'dashboard/analytics',
        name: 'Analytics',
        component: () => import('@/views/dashboard/AnalyticsPage.vue'),
        meta: { title: '数据分析' },
      },
      // System group
      {
        path: 'system/user',
        name: 'UserManagement',
        component: () => import('@/views/system/UserManagement.vue'),
        meta: { title: '用户管理' },
      },
      {
        path: 'system/role',
        name: 'RoleManagement',
        component: () => import('@/views/system/RoleManagement.vue'),
        meta: { title: '角色管理' },
      },
      {
        path: 'system/menu',
        name: 'MenuManagement',
        component: () => import('@/views/system/MenuManagement.vue'),
        meta: { title: '菜单管理' },
      },
      {
        path: 'system/department',
        name: 'DepartmentManagement',
        component: () => import('@/views/system/DepartmentManagement.vue'),
        meta: { title: '部门管理' },
      },
      // Content group
      {
        path: 'content/article',
        name: 'ArticleManagement',
        component: () => import('@/views/content/ArticleManagement.vue'),
        meta: { title: '文章管理' },
      },
      {
        path: 'content/category',
        name: 'CategoryManagement',
        component: () => import('@/views/content/CategoryManagement.vue'),
        meta: { title: '分类管理' },
      },
      {
        path: 'content/tag',
        name: 'TagManagement',
        component: () => import('@/views/content/TagManagement.vue'),
        meta: { title: '标签管理' },
      },
      // Components group
      {
        path: 'components/editor',
        name: 'EditorDemo',
        component: () => import('@/views/components/EditorDemo.vue'),
        meta: { title: '富文本编辑器' },
      },
      {
        path: 'components/drag',
        name: 'DragDemo',
        component: () => import('@/views/components/DragDemo.vue'),
        meta: { title: '拖拽列表' },
      },
      {
        path: 'components/icons',
        name: 'IconsDemo',
        component: () => import('@/views/components/IconsDemo.vue'),
        meta: { title: '图标展示' },
      },
      // Charts group - 25 chart types
      {
        path: 'charts/line',
        name: 'LineChart',
        component: () => import('@/views/charts/LineChart.vue'),
        meta: { title: '折线图' },
      },
      {
        path: 'charts/area',
        name: 'AreaChart',
        component: () => import('@/views/charts/AreaChart.vue'),
        meta: { title: '面积图' },
      },
      {
        path: 'charts/bar',
        name: 'BarChart',
        component: () => import('@/views/charts/BarChart.vue'),
        meta: { title: '柱状图' },
      },
      {
        path: 'charts/horizontal-bar',
        name: 'HorizontalBar',
        component: () => import('@/views/charts/HorizontalBar.vue'),
        meta: { title: '横向柱状图' },
      },
      {
        path: 'charts/pie',
        name: 'PieChart',
        component: () => import('@/views/charts/PieChart.vue'),
        meta: { title: '饼图' },
      },
      {
        path: 'charts/doughnut',
        name: 'DoughnutChart',
        component: () => import('@/views/charts/DoughnutChart.vue'),
        meta: { title: '环形图' },
      },
      {
        path: 'charts/scatter',
        name: 'ScatterChart',
        component: () => import('@/views/charts/ScatterChart.vue'),
        meta: { title: '散点图' },
      },
      {
        path: 'charts/radar',
        name: 'RadarChart',
        component: () => import('@/views/charts/RadarChart.vue'),
        meta: { title: '雷达图' },
      },
      {
        path: 'charts/funnel',
        name: 'FunnelChart',
        component: () => import('@/views/charts/FunnelChart.vue'),
        meta: { title: '漏斗图' },
      },
      {
        path: 'charts/gauge',
        name: 'GaugeChart',
        component: () => import('@/views/charts/GaugeChart.vue'),
        meta: { title: '仪表盘图' },
      },
      {
        path: 'charts/heatmap',
        name: 'HeatmapChart',
        component: () => import('@/views/charts/HeatmapChart.vue'),
        meta: { title: '热力图' },
      },
      {
        path: 'charts/treemap',
        name: 'TreemapChart',
        component: () => import('@/views/charts/TreemapChart.vue'),
        meta: { title: '矩形树图' },
      },
      {
        path: 'charts/sunburst',
        name: 'SunburstChart',
        component: () => import('@/views/charts/SunburstChart.vue'),
        meta: { title: '旭日图' },
      },
      {
        path: 'charts/sankey',
        name: 'SankeyChart',
        component: () => import('@/views/charts/SankeyChart.vue'),
        meta: { title: '桑基图' },
      },
      {
        path: 'charts/candlestick',
        name: 'CandlestickChart',
        component: () => import('@/views/charts/CandlestickChart.vue'),
        meta: { title: 'K线图' },
      },
      {
        path: 'charts/boxplot',
        name: 'BoxplotChart',
        component: () => import('@/views/charts/BoxplotChart.vue'),
        meta: { title: '箱线图' },
      },
      {
        path: 'charts/waterfall',
        name: 'WaterfallChart',
        component: () => import('@/views/charts/WaterfallChart.vue'),
        meta: { title: '瀑布图' },
      },
      {
        path: 'charts/mixed',
        name: 'MixedChart',
        component: () => import('@/views/charts/MixedChart.vue'),
        meta: { title: '混合图' },
      },
      {
        path: 'charts/stacked-bar',
        name: 'StackedBar',
        component: () => import('@/views/charts/StackedBar.vue'),
        meta: { title: '堆叠柱状图' },
      },
      {
        path: 'charts/stacked-area',
        name: 'StackedArea',
        component: () => import('@/views/charts/StackedArea.vue'),
        meta: { title: '堆叠面积图' },
      },
      {
        path: 'charts/polar',
        name: 'PolarChart',
        component: () => import('@/views/charts/PolarChart.vue'),
        meta: { title: '极坐标图' },
      },
      {
        path: 'charts/rose',
        name: 'RoseChart',
        component: () => import('@/views/charts/RoseChart.vue'),
        meta: { title: '南丁格尔玫瑰图' },
      },
      {
        path: 'charts/parallel',
        name: 'ParallelChart',
        component: () => import('@/views/charts/ParallelChart.vue'),
        meta: { title: '平行坐标图' },
      },
      {
        path: 'charts/theme-river',
        name: 'ThemeRiverChart',
        component: () => import('@/views/charts/ThemeRiverChart.vue'),
        meta: { title: '主题河流图' },
      },
      {
        path: 'charts/graph',
        name: 'GraphChart',
        component: () => import('@/views/charts/GraphChart.vue'),
        meta: { title: '关系图' },
      },
      // Hooks group
      { path: 'hooks/use-loading', name: 'UseLoadingDemo', component: () => import('@/views/hooks/UseLoadingDemo.vue'), meta: { title: 'useLoading' } },
      { path: 'hooks/use-pagination', name: 'UsePaginationDemo', component: () => import('@/views/hooks/UsePaginationDemo.vue'), meta: { title: 'usePagination' } },
      { path: 'hooks/use-permission', name: 'UsePermissionDemo', component: () => import('@/views/hooks/UsePermissionDemo.vue'), meta: { title: 'usePermission' } },
      { path: 'hooks/use-sms-countdown', name: 'UseSmsCountdownDemo', component: () => import('@/views/hooks/UseSmsCountdownDemo.vue'), meta: { title: 'useSmsCountdown' } },
      { path: 'hooks/use-local-storage', name: 'UseLocalStorageDemo', component: () => import('@/views/hooks/UseLocalStorageDemo.vue'), meta: { title: 'useLocalStorage' } },
      { path: 'hooks/use-clipboard', name: 'UseClipboardDemo', component: () => import('@/views/hooks/UseClipboardDemo.vue'), meta: { title: 'useClipboard' } },
      { path: 'hooks/use-debounce-fn', name: 'UseDebounceFnDemo', component: () => import('@/views/hooks/UseDebounceFnDemo.vue'), meta: { title: 'useDebounceFn' } },
      { path: 'hooks/use-throttle-fn', name: 'UseThrottleFnDemo', component: () => import('@/views/hooks/UseThrottleFnDemo.vue'), meta: { title: 'useThrottleFn' } },
      { path: 'hooks/use-window-size', name: 'UseWindowSizeDemo', component: () => import('@/views/hooks/UseWindowSizeDemo.vue'), meta: { title: 'useWindowSize' } },
      { path: 'hooks/use-event-listener', name: 'UseEventListenerDemo', component: () => import('@/views/hooks/UseEventListenerDemo.vue'), meta: { title: 'useEventListener' } },
      // Features group
      {
        path: 'features/i18n',
        name: 'I18nDemo',
        component: () => import('@/views/features/I18nDemo.vue'),
        meta: { title: '国际化' },
      },
      {
        path: 'features/clipboard',
        name: 'ClipboardDemo',
        component: () => import('@/views/features/ClipboardDemo.vue'),
        meta: { title: '剪贴板' },
      },
      {
        path: 'features/print',
        name: 'PrintDemo',
        component: () => import('@/views/features/PrintDemo.vue'),
        meta: { title: '打印' },
      },
      {
        path: 'features/dayjs',
        name: 'DayjsDemo',
        component: () => import('@/views/features/DayjsDemo.vue'),
        meta: { title: 'dayjs 日期处理' },
      },
      {
        path: 'features/lodash',
        name: 'LodashDemo',
        component: () => import('@/views/features/LodashDemo.vue'),
        meta: { title: 'lodash 工具函数' },
      },
      // Components - Charts overview
      {
        path: 'components/charts',
        name: 'ChartsDemo',
        component: () => import('@/views/components/ChartsDemo.vue'),
        meta: { title: '图表概览' },
      },
      // UI Components
      { path: 'ui/button', name: 'ButtonDemo', component: () => import('@/views/ui/ButtonDemo.vue'), meta: { title: 'Button 按钮' } },
      { path: 'ui/input', name: 'InputDemo', component: () => import('@/views/ui/InputDemo.vue'), meta: { title: 'Input 输入框' } },
      { path: 'ui/form', name: 'FormDemo', component: () => import('@/views/ui/FormDemo.vue'), meta: { title: 'Form 表单' } },
      { path: 'ui/table', name: 'TableDemo', component: () => import('@/views/ui/TableDemo.vue'), meta: { title: 'Table 表格' } },
      { path: 'ui/modal', name: 'ModalDemo', component: () => import('@/views/ui/ModalDemo.vue'), meta: { title: 'Modal 模态框' } },
      { path: 'ui/drawer', name: 'DrawerDemo', component: () => import('@/views/ui/DrawerDemo.vue'), meta: { title: 'Drawer 抽屉' } },
      { path: 'ui/message', name: 'MessageDemo', component: () => import('@/views/ui/MessageDemo.vue'), meta: { title: 'Message 消息' } },
      { path: 'ui/notification', name: 'NotificationDemo', component: () => import('@/views/ui/NotificationDemo.vue'), meta: { title: 'Notification 通知' } },
      { path: 'ui/dialog', name: 'DialogDemo', component: () => import('@/views/ui/DialogDemo.vue'), meta: { title: 'Dialog 对话框' } },
      { path: 'ui/tabs', name: 'TabsDemo', component: () => import('@/views/ui/TabsDemo.vue'), meta: { title: 'Tabs 标签页' } },
      { path: 'ui/tag', name: 'TagDemo', component: () => import('@/views/ui/TagDemo.vue'), meta: { title: 'Tag 标签' } },
      { path: 'ui/select', name: 'SelectDemo', component: () => import('@/views/ui/SelectDemo.vue'), meta: { title: 'Select 选择器' } },
      { path: 'ui/date-picker', name: 'DatePickerDemo', component: () => import('@/views/ui/DatePickerDemo.vue'), meta: { title: 'DatePicker 日期选择' } },
      { path: 'ui/upload', name: 'UploadDemo', component: () => import('@/views/ui/UploadDemo.vue'), meta: { title: 'Upload 上传' } },
      { path: 'ui/tree', name: 'TreeDemo', component: () => import('@/views/ui/TreeDemo.vue'), meta: { title: 'Tree 树形控件' } },
      { path: 'ui/card', name: 'CardDemo', component: () => import('@/views/ui/CardDemo.vue'), meta: { title: 'Card 卡片' } },
      { path: 'ui/avatar', name: 'AvatarDemo', component: () => import('@/views/ui/AvatarDemo.vue'), meta: { title: 'Avatar 头像' } },
      { path: 'ui/badge', name: 'BadgeDemo', component: () => import('@/views/ui/BadgeDemo.vue'), meta: { title: 'Badge 徽标' } },
      { path: 'ui/progress', name: 'ProgressDemo', component: () => import('@/views/ui/ProgressDemo.vue'), meta: { title: 'Progress 进度条' } },
      { path: 'ui/timeline', name: 'TimelineDemo', component: () => import('@/views/ui/TimelineDemo.vue'), meta: { title: 'Timeline 时间线' } },
      { path: 'ui/alert', name: 'AlertDemo', component: () => import('@/views/ui/AlertDemo.vue'), meta: { title: 'Alert 警告' } },
      { path: 'ui/popover', name: 'PopoverDemo', component: () => import('@/views/ui/PopoverDemo.vue'), meta: { title: 'Popover 弹出框' } },
      { path: 'ui/tooltip', name: 'TooltipDemo', component: () => import('@/views/ui/TooltipDemo.vue'), meta: { title: 'Tooltip 文字提示' } },
      { path: 'ui/switch', name: 'SwitchDemo', component: () => import('@/views/ui/SwitchDemo.vue'), meta: { title: 'Switch 开关' } },
      { path: 'ui/slider', name: 'SliderDemo', component: () => import('@/views/ui/SliderDemo.vue'), meta: { title: 'Slider 滑块' } },
      { path: 'ui/transfer', name: 'TransferDemo', component: () => import('@/views/ui/TransferDemo.vue'), meta: { title: 'Transfer 穿梭框' } },
      { path: 'ui/collapse', name: 'CollapseDemo', component: () => import('@/views/ui/CollapseDemo.vue'), meta: { title: 'Collapse 折叠面板' } },
      { path: 'ui/dropdown', name: 'DropdownDemo', component: () => import('@/views/ui/DropdownDemo.vue'), meta: { title: 'Dropdown 下拉菜单' } },
      { path: 'ui/pagination', name: 'PaginationDemo', component: () => import('@/views/ui/PaginationDemo.vue'), meta: { title: 'Pagination 分页' } },
      { path: 'ui/steps', name: 'StepsDemo', component: () => import('@/views/ui/StepsDemo.vue'), meta: { title: 'Steps 步骤条' } },
      { path: 'ui/carousel', name: 'CarouselDemo', component: () => import('@/views/ui/CarouselDemo.vue'), meta: { title: 'Carousel 走马灯' } },
      { path: 'ui/descriptions', name: 'DescriptionsDemo', component: () => import('@/views/ui/DescriptionsDemo.vue'), meta: { title: 'Descriptions 描述列表' } },
      { path: 'ui/result', name: 'ResultDemo', component: () => import('@/views/ui/ResultDemo.vue'), meta: { title: 'Result 结果' } },
      { path: 'ui/skeleton', name: 'SkeletonDemo', component: () => import('@/views/ui/SkeletonDemo.vue'), meta: { title: 'Skeleton 骨架屏' } },
      { path: 'ui/spin', name: 'SpinDemo', component: () => import('@/views/ui/SpinDemo.vue'), meta: { title: 'Spin 加载' } },
      { path: 'ui/empty', name: 'EmptyDemo', component: () => import('@/views/ui/EmptyDemo.vue'), meta: { title: 'Empty 空状态' } },
      { path: 'ui/divider', name: 'DividerDemo', component: () => import('@/views/ui/DividerDemo.vue'), meta: { title: 'Divider 分割线' } },
      { path: 'ui/breadcrumb', name: 'BreadcrumbDemo', component: () => import('@/views/ui/BreadcrumbDemo.vue'), meta: { title: 'Breadcrumb 面包屑' } },
      { path: 'ui/menu', name: 'MenuDemo', component: () => import('@/views/ui/MenuDemo.vue'), meta: { title: 'Menu 菜单' } },
      { path: 'ui/color-picker', name: 'ColorPickerDemo', component: () => import('@/views/ui/ColorPickerDemo.vue'), meta: { title: 'ColorPicker 颜色选择' } },
      // Permission
      {
        path: 'permission-management',
        name: 'PermissionManagement',
        component: () => import('@/views/permission/PermissionManagement.vue'),
        meta: { title: '权限管理' },
      },
      {
        path: 'permission/demo',
        name: 'PermissionDemo',
        component: () => import('@/views/permission/PermissionDemo.vue'),
        meta: { title: '权限演示' },
      },
      // About
      {
        path: 'about',
        name: 'About',
        component: () => import('@/views/about/AboutPage.vue'),
        meta: { title: '关于' },
      },
    ],
  },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/LoginPage.vue'),
    meta: { title: '登录' },
  },
  {
    path: '/register',
    name: 'Register',
    component: () => import('@/views/register/RegisterPage.vue'),
    meta: { title: '注册' },
  },
  {
    path: '/401',
    name: 'Error401',
    component: () => import('@/views/error/Error401.vue'),
    meta: { title: '401' },
  },
  {
    path: '/403',
    name: 'Error403',
    component: () => import('@/views/error/Error403.vue'),
    meta: { title: '403' },
  },
  {
    path: '/404',
    name: 'Error404',
    component: () => import('@/views/error/Error404.vue'),
    meta: { title: '404' },
  },
  {
    path: '/500',
    name: 'Error500',
    component: () => import('@/views/error/Error500.vue'),
    meta: { title: '500' },
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes: staticRoutes,
})

export default router
